// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';

export function AppData():Promise<process.AppData>;

export function OpenDirectoryDialogSetOutput():Promise<void>;

export function OpenMultipleVideoFilesDialog():Promise<void>;

export function OpenOutputDirectory():Promise<void>;

export function OpenWatermarkImageDialog():Promise<void>;

export function Transcode(arg1:string,arg2:string,arg3:process.TranscodeParams):Promise<string>;
