// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppData() {
  return window['go']['process']['App']['AppData']();
}

export function OpenDirectoryDialogSetOutput() {
  return window['go']['process']['App']['OpenDirectoryDialogSetOutput']();
}

export function OpenMultipleVideoFilesDialog() {
  return window['go']['process']['App']['OpenMultipleVideoFilesDialog']();
}

export function OpenOutputDirectory() {
  return window['go']['process']['App']['OpenOutputDirectory']();
}

export function OpenTranscodeVideo(arg1) {
  return window['go']['process']['App']['OpenTranscodeVideo'](arg1);
}

export function OpenWatermarkImageDialog() {
  return window['go']['process']['App']['OpenWatermarkImageDialog']();
}

export function Transcode(arg1, arg2, arg3) {
  return window['go']['process']['App']['Transcode'](arg1, arg2, arg3);
}
